// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketing.Backend.Infrastructure.Data;

#nullable disable

namespace Ticketing.Backend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214121545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("FileName")
                        .IsRequired();
                    b.Property<string>("FileUrl")
                        .IsRequired();
                    b.Property<Guid>("TicketId");
                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("Description");
                    b.Property<bool>("IsActive");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<bool>("IsRead");
                    b.Property<string>("Message")
                        .IsRequired();
                    b.Property<Guid>("UserId");
                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<int>("CategoryId");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("Description");
                    b.Property<bool>("IsActive");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<bool>("AllowClientAttachments");
                    b.Property<string>("AllowedEmailDomains")
                        .IsRequired();
                    b.Property<string>("AppName")
                        .IsRequired();
                    b.Property<bool>("AutoAssignEnabled");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("DefaultLanguage")
                        .IsRequired();
                    b.Property<int>("DefaultPriority");
                    b.Property<int>("DefaultStatus");
                    b.Property<string>("DefaultTheme")
                        .IsRequired();
                    b.Property<bool>("EmailNotificationsEnabled");
                    b.Property<int>("MaxAttachmentSizeMB");
                    b.Property<bool>("NotifyOnTicketAssigned");
                    b.Property<bool>("NotifyOnTicketClosed");
                    b.Property<bool>("NotifyOnTicketCreated");
                    b.Property<bool>("NotifyOnTicketReplied");
                    b.Property<int>("PasswordMinLength");
                    b.Property<bool>("Require2FA");
                    b.Property<int>("ResponseSlaHours");
                    b.Property<int>("SessionTimeoutMinutes");
                    b.Property<bool>("SmsNotificationsEnabled");
                    b.Property<string>("SupportEmail")
                        .IsRequired();
                    b.Property<string>("SupportPhone")
                        .IsRequired();
                    b.Property<string>("Timezone")
                        .IsRequired();
                    b.Property<DateTime>("UpdatedAt");
                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("Department")
                        .HasMaxLength(100);
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);
                    b.Property<Guid?>("UserId");
                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<Guid?>("AssignedToUserId");
                    b.Property<int>("CategoryId");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<Guid>("CreatedByUserId");
                    b.Property<string>("Description")
                        .IsRequired();
                    b.Property<DateTime?>("DueDate");
                    b.Property<int>("Priority");
                    b.Property<int>("Status");
                    b.Property<int?>("SubcategoryId");
                    b.Property<Guid?>("TechnicianId");
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300);
                    b.Property<DateTime?>("UpdatedAt");
                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<Guid>("AuthorUserId");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("Message")
                        .IsRequired();
                    b.Property<int?>("Status");
                    b.Property<Guid>("TicketId");
                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMessages");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(8192);
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("Department")
                        .HasMaxLength(200);
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<string>("PasswordHash")
                        .IsRequired();
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50);
                    b.Property<int>("Role");
                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<bool>("DesktopEnabled");
                    b.Property<bool>("EmailEnabled");
                    b.Property<string>("FontSize")
                        .IsRequired()
                        .HasMaxLength(10);
                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10);
                    b.Property<bool>("PushEnabled");
                    b.Property<bool>("SmsEnabled");
                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20);
                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100);
                    b.Property<DateTime>("UpdatedAt");
                    b.Property<Guid>("UserId");
                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Subcategory", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Technician", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "AssignedToUser")
                        .WithMany("TicketsAssigned")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ticketing.Backend.Domain.Entities.Category", "Category")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "CreatedByUser")
                        .WithMany("TicketsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany("Tickets")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ticketing.Backend.Domain.Entities.Technician", "Technician")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToUser");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Subcategory");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketMessage", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "AuthorUser")
                        .WithMany("Messages")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Ticketing.Backend.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Subcategory", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Technician", b =>
                {
                    b.Navigation("AssignedTickets");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Preferences");

                    b.Navigation("TicketsAssigned");

                    b.Navigation("TicketsCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
