// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketing.Backend.Infrastructure.Data;

#nullable disable

namespace Ticketing.Backend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260124150000_AddSupervisorTechnicianLinks")]
    partial class AddSupervisorTechnicianLinks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.SupervisorTechnicianLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<Guid>("SupervisorUserId");
                    b.Property<Guid>("TechnicianUserId");
                    b.HasKey("Id");

                    b.HasIndex("SupervisorUserId", "TechnicianUserId")
                        .IsUnique();

                    b.HasIndex("TechnicianUserId");

                    b.ToTable("SupervisorTechnicianLinks");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.SupervisorTechnicianLink", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "SupervisorUser")
                        .WithMany()
                        .HasForeignKey("SupervisorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "TechnicianUser")
                        .WithMany()
                        .HasForeignKey("TechnicianUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupervisorUser");
                    b.Navigation("TechnicianUser");
                });
#pragma warning restore 612, 618
        }
    }
}

