// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketing.Backend.Infrastructure.Data;

#nullable disable

namespace Ticketing.Backend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("FileName")
                        .IsRequired();
                    b.Property<string>("FileUrl")
                        .IsRequired();
                    b.Property<Guid>("TicketId");
                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("Description");
                    b.Property<bool>("IsActive");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.CategoryFieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<int>("CategoryId");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500);
                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100);
                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<double?>("Max");
                    b.Property<double?>("Min");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<string>("OptionsJson");
                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired();
                    b.Property<DateTime?>("UpdatedAt");
                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CategoryId", "Key")
                        .IsUnique();

                    b.ToTable("CategoryFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<int>("CategoryId");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("Description");
                    b.Property<bool>("IsActive");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.SubcategoryFieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500);
                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(100);
                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<double?>("Max");
                    b.Property<double?>("Min");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<string>("OptionsJson");
                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("SubcategoryId");
                    b.Property<string>("Type")
                        .IsRequired();
                    b.Property<DateTime?>("UpdatedAt");
                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("SubcategoryId", "FieldKey")
                        .IsUnique();

                    b.ToTable("SubcategoryFieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.SupervisorTechnicianLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<Guid>("SupervisorUserId");
                    b.Property<Guid>("TechnicianUserId");
                    b.HasKey("Id");

                    b.HasIndex("TechnicianUserId");

                    b.HasIndex("SupervisorUserId", "TechnicianUserId")
                        .IsUnique();

                    b.ToTable("SupervisorTechnicianLinks", (string)null);
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<bool>("AllowClientAttachments");
                    b.Property<string>("AllowedEmailDomains")
                        .IsRequired();
                    b.Property<string>("AppName")
                        .IsRequired();
                    b.Property<bool>("AutoAssignEnabled");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("DefaultLanguage")
                        .IsRequired();
                    b.Property<int>("DefaultPriority");
                    b.Property<int>("DefaultStatus");
                    b.Property<string>("DefaultTheme")
                        .IsRequired();
                    b.Property<bool>("EmailNotificationsEnabled");
                    b.Property<int>("MaxAttachmentSizeMB");
                    b.Property<bool>("NotifyOnTicketAssigned");
                    b.Property<bool>("NotifyOnTicketClosed");
                    b.Property<bool>("NotifyOnTicketCreated");
                    b.Property<bool>("NotifyOnTicketReplied");
                    b.Property<int>("PasswordMinLength");
                    b.Property<bool>("Require2FA");
                    b.Property<int>("ResponseSlaHours");
                    b.Property<int>("SessionTimeoutMinutes");
                    b.Property<bool>("SmsNotificationsEnabled");
                    b.Property<string>("SupportEmail")
                        .IsRequired();
                    b.Property<string>("SupportPhone")
                        .IsRequired();
                    b.Property<string>("Timezone")
                        .IsRequired();
                    b.Property<DateTime>("UpdatedAt");
                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<DateTime?>("DeletedAt");
                    b.Property<Guid?>("DeletedByUserId");
                    b.Property<string>("Department")
                        .HasMaxLength(100);
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSupervisor")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);
                    b.Property<Guid?>("UserId");
                    b.HasKey("Id");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TechnicianSubcategoryPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<int>("SubcategoryId");
                    b.Property<Guid>("TechnicianId");
                    b.Property<DateTime?>("UpdatedAt");
                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("TechnicianId", "SubcategoryId")
                        .IsUnique();

                    b.ToTable("TechnicianSubcategoryPermissions");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<Guid?>("AssignedToUserId");
                    b.Property<int>("CategoryId");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<Guid>("CreatedByUserId");
                    b.Property<string>("Description")
                        .IsRequired();
                    b.Property<DateTime?>("DueDate");
                    b.Property<int>("Priority");
                    b.Property<int>("Status");
                    b.Property<int?>("SubcategoryId");
                    b.Property<Guid?>("TechnicianId");
                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300);
                    b.Property<DateTime?>("UpdatedAt");
                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50);
                    b.Property<Guid>("ActorUserId");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100);
                    b.Property<string>("MetadataJson")
                        .HasMaxLength(2000);
                    b.Property<string>("NewStatus")
                        .HasMaxLength(50);
                    b.Property<string>("OldStatus")
                        .HasMaxLength(50);
                    b.Property<Guid>("TicketId");
                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TicketId");

                    b.HasIndex("TicketId", "CreatedAt");

                    b.ToTable("TicketActivityEvents", (string)null);
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<int>("FieldDefinitionId");
                    b.Property<Guid>("TicketId");
                    b.Property<DateTime?>("UpdatedAt");
                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000);
                    b.HasKey("Id");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("TicketId");

                    b.HasIndex("TicketId", "FieldDefinitionId")
                        .IsUnique();

                    b.ToTable("TicketFieldValues", (string)null);
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<Guid>("AuthorUserId");
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("Message")
                        .IsRequired();
                    b.Property<int?>("Status");
                    b.Property<Guid>("TicketId");
                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMessages");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketTechnicianAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime?>("AcceptedAt");
                    b.Property<DateTime>("AssignedAt");
                    b.Property<Guid>("AssignedByUserId");
                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Role")
                        .HasMaxLength(50);
                    b.Property<Guid?>("TechnicianId");
                    b.Property<Guid>("TechnicianUserId");
                    b.Property<Guid>("TicketId");
                    b.Property<DateTime?>("UpdatedAt");
                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("TechnicianUserId");

                    b.HasIndex("TicketId");

                    b.HasIndex("TicketId", "TechnicianUserId", "IsActive");

                    b.ToTable("TicketTechnicianAssignments", (string)null);
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketUserState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime?>("LastSeenAt");
                    b.Property<Guid>("TicketId");
                    b.Property<Guid>("UserId");
                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TicketId", "UserId")
                        .IsUnique();

                    b.ToTable("TicketUserStates", (string)null);
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(8192);
                    b.Property<DateTime>("CreatedAt");
                    b.Property<string>("Department")
                        .HasMaxLength(200);
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200);
                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LockoutEnd");
                    b.Property<string>("PasswordHash")
                        .IsRequired();
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50);
                    b.Property<int>("Role");
                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(256);
                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();
                    b.Property<DateTime>("CreatedAt");
                    b.Property<bool>("DesktopEnabled");
                    b.Property<bool>("EmailEnabled");
                    b.Property<string>("FontSize")
                        .IsRequired()
                        .HasMaxLength(10);
                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10);
                    b.Property<bool>("PushEnabled");
                    b.Property<bool>("SmsEnabled");
                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20);
                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100);
                    b.Property<DateTime>("UpdatedAt");
                    b.Property<Guid>("UserId");
                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.CategoryFieldDefinition", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Subcategory", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.SubcategoryFieldDefinition", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.SupervisorTechnicianLink", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "SupervisorUser")
                        .WithMany()
                        .HasForeignKey("SupervisorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "TechnicianUser")
                        .WithMany()
                        .HasForeignKey("TechnicianUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SupervisorUser");

                    b.Navigation("TechnicianUser");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Technician", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeletedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TechnicianSubcategoryPermission", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.Technician", "Technician")
                        .WithMany("SubcategoryPermissions")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "AssignedToUser")
                        .WithMany("TicketsAssigned")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ticketing.Backend.Domain.Entities.Category", "Category")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "CreatedByUser")
                        .WithMany("TicketsCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.Subcategory", "Subcategory")
                        .WithMany("Tickets")
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ticketing.Backend.Domain.Entities.Technician", "Technician")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToUser");

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Subcategory");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketActivityEvent", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.Ticket", "Ticket")
                        .WithMany("ActivityEvents")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketFieldValue", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.SubcategoryFieldDefinition", "FieldDefinition")
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.Ticket", "Ticket")
                        .WithMany("FieldValues")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldDefinition");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketMessage", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "AuthorUser")
                        .WithMany("Messages")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketTechnicianAssignment", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "TechnicianUser")
                        .WithMany()
                        .HasForeignKey("TechnicianUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.Ticket", "Ticket")
                        .WithMany("AssignedTechnicians")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Technician");

                    b.Navigation("TechnicianUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.TicketUserState", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("Ticketing.Backend.Domain.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Ticketing.Backend.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Subcategory", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Technician", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("SubcategoryPermissions");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("ActivityEvents");

                    b.Navigation("AssignedTechnicians");

                    b.Navigation("Attachments");

                    b.Navigation("FieldValues");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Ticketing.Backend.Domain.Entities.User", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Preferences");

                    b.Navigation("TicketsAssigned");

                    b.Navigation("TicketsCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
